/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-09-20 15:41:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String userName = (String) session.getAttribute("userName");
    if (userName == null || userName.isEmpty()) userName = "Guest";
    String firstName = userName.contains(" ") ? userName.split(" ")[0] : userName;
    String userRole = (String) session.getAttribute("userRole");
    boolean isOwner = "RESTAURANT_OWNER".equals(userRole);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>BenedictJeromeMart - Home</title>\n");
      out.write("    <meta name=\"description\" content=\"Order delicious food online from BenedictJeromeMart\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     WELCOME TOAST\n");
      out.write("     ========================================================= -->\n");
      out.write("<div id=\"welcomeToast\">\n");
      out.write("    <span class=\"toast-emoji\">👋</span>\n");
      out.write("    <span>\n");
      out.write("        Welcome back, ");
      out.print( firstName );
      out.write("!\n");
      out.write("        Let's find something tasty.\n");
      out.write("    </span>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     NAVBAR\n");
      out.write("     ========================================================= -->\n");
      out.write("<header class=\"navbar\">\n");
      out.write("    <a href=\"#\" class=\"brand\">\n");
      out.write("        <div class=\"brand-icon\">🛒</div>\n");
      out.write("        BenedictJeromeMart\n");
      out.write("    </a>\n");
      out.write("    <div class=\"nav-right\">\n");
      out.write("        <a href=\"orders.jsp\" class=\"btn btn-outline-sm\">My Orders</a>\n");
      out.write("        ");
 if (isOwner) { 
      out.write("\n");
      out.write("        <a href=\"manage-menu.jsp\" class=\"btn btn-outline-sm\">Manage Menu</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <div class=\"welcome-badge\">\n");
      out.write("            <span class=\"welcome-avatar\">");
      out.print( firstName.charAt(0) );
      out.write("</span>\n");
      out.write("            Hey, <strong>");
      out.print( firstName );
      out.write("</strong>! 👋\n");
      out.write("        </div>\n");
      out.write("        <a href=\"#\" onclick=\"doLogout(); return false;\" class=\"btn btn-outline-sm\">🚪 Logout</a>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     HERO BANNER\n");
      out.write("     ========================================================= -->\n");
      out.write("<section class=\"hero-banner\">\n");
      out.write("    <div class=\"hero-content\">\n");
      out.write("        <p class=\"hero-tag\">🍽️ Fresh &amp; Delicious</p>\n");
      out.write("        <h1>Welcome back, <span class=\"hero-name\">");
      out.print( firstName );
      out.write("</span>!</h1>\n");
      out.write("        <p class=\"hero-sub\">What are you craving today? Pick your favourite and we'll get it to you!</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"hero-art\">🍕🍔🍜🥗🍛🥤</div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     CATEGORY TABS\n");
      out.write("     ========================================================= -->\n");
      out.write("<div class=\"category-section\">\n");
      out.write("    <div class=\"category-tabs\" id=\"categoryTabs\">\n");
      out.write("        <button class=\"category-tab active\" onclick=\"filterByCategory('all')\" data-cat=\"all\" id=\"tab-all\">\n");
      out.write("            🍽️ All\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     MAIN LAYOUT\n");
      out.write("     ========================================================= -->\n");
      out.write("<main class=\"main-layout\">\n");
      out.write("\n");
      out.write("    <!-- =====================================================\n");
      out.write("         MENU SECTION\n");
      out.write("         ===================================================== -->\n");
      out.write("    <section>\n");
      out.write("        <!-- ZOMATO STYLE AI ASSISTANT -->\n");
      out.write("        <div class=\"ai-assistant-card\">\n");
      out.write("            <div class=\"ai-header\">\n");
      out.write("                <div class=\"ai-avatar\">✨</div>\n");
      out.write("                <div>\n");
      out.write("                    <strong style=\"font-size:1.15rem;display:block;\">Zomato-Style Food AI</strong>\n");
      out.write("                    <span style=\"font-size:0.85rem;color:var(--text-muted);\">Ask for recommendations based on taste, budget, or dietary needs!</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"ai-input-wrapper\">\n");
      out.write("                <input type=\"text\" id=\"aiQuery\" class=\"ai-input\" placeholder=\"e.g. Cheesy burger under Rs. 250 or Spicy North Indian...\">\n");
      out.write("                <button onclick=\"askAI()\" class=\"btn btn-outline-sm\">Search AI</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"ai-quick-prompts\">\n");
      out.write("                <span class=\"ai-chip\" onclick=\"quickSearch('Cheesy & Juicy')\">🧀 Cheesy &amp; Juicy</span>\n");
      out.write("                <span class=\"ai-chip\" onclick=\"quickSearch('Spicy')\">🌶️ Spicy Feasts</span>\n");
      out.write("                <span class=\"ai-chip\" onclick=\"quickSearch('Under 250')\">💰 Under Rs. 250</span>\n");
      out.write("                <span class=\"ai-chip\" onclick=\"quickSearch('Desserts')\">🍰 Sweet Cravings</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- MENU TITLE -->\n");
      out.write("        <h2 class=\"section-title\">\n");
      out.write("            <span id=\"sectionEmoji\">🔥</span>\n");
      out.write("            <span id=\"sectionLabel\">Explore Delicious Menu</span>\n");
      out.write("        </h2>\n");
      out.write("\n");
      out.write("        <!-- MENU LIST -->\n");
      out.write("        <div id=\"menuList\" class=\"menu-grid\">\n");
      out.write("            <div class=\"loading-spinner\">\n");
      out.write("                <div class=\"spinner\"></div>\n");
      out.write("                <p>Loading mouth-watering food...</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- =====================================================\n");
      out.write("         CART PANEL\n");
      out.write("         ===================================================== -->\n");
      out.write("    <aside>\n");
      out.write("        <div class=\"cart-panel\">\n");
      out.write("            <h2 class=\"section-title\" style=\"font-size:1.2rem;\">\n");
      out.write("                🛒 Your Cart\n");
      out.write("                <span class=\"cart-badge\" id=\"cartBadge\" style=\"display:none;\">0</span>\n");
      out.write("            </h2>\n");
      out.write("            <div id=\"cartItems\">\n");
      out.write("                <div class=\"empty-cart-msg\">\n");
      out.write("                    <span style=\"font-size:2.5rem;\">🛒</span>\n");
      out.write("                    <p>Your cart is empty</p>\n");
      out.write("                    <small>Add items from the menu</small>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- PRICE BREAKDOWN -->\n");
      out.write("            <div class=\"cart-summary\" id=\"cartSummary\" style=\"display:none;\">\n");
      out.write("                <div class=\"cart-row\">\n");
      out.write("                    <span>Subtotal</span>\n");
      out.write("                    <span id=\"cartSubtotal\">Rs. 0.00</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"cart-row\">\n");
      out.write("                    <span>GST (5%)</span>\n");
      out.write("                    <span id=\"cartTax\">Rs. 0.00</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"cart-row delivery-row\">\n");
      out.write("                    <span>Delivery</span>\n");
      out.write("                    <span class=\"free-tag\">FREE</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"cart-total\">\n");
      out.write("                    <span>Total</span>\n");
      out.write("                    <span id=\"cartTotal\">Rs. 0.00</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <button onclick=\"openPayment()\" class=\"btn btn-primary\" id=\"payBtn\" disabled>💳 Proceed to Pay</button>\n");
      out.write("            <div id=\"message\"></div>\n");
      out.write("        </div>\n");
      out.write("    </aside>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     PAYMENT MODAL\n");
      out.write("     ========================================================= -->\n");
      out.write("<div class=\"modal-overlay\" id=\"paymentModal\">\n");
      out.write("    <div class=\"modal\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("            <h2>💳 Payment</h2>\n");
      out.write("            <button onclick=\"closePayment()\" class=\"modal-close\" id=\"modalCloseBtn\">✕</button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"payment-total-banner\">\n");
      out.write("            <span>Order Total</span>\n");
      out.write("            <strong id=\"modalTotal\">Rs. 0.00</strong>\n");
      out.write("        </div>\n");
      out.write("        <p style=\"font-size:0.85rem;color:var(--text-muted);margin-bottom:1rem;\">Choose your payment method:</p>\n");
      out.write("\n");
      out.write("        <!-- PAYMENT OPTIONS -->\n");
      out.write("        <div class=\"payment-options\">\n");
      out.write("            <div class=\"payment-option selected\" onclick=\"selectPayment('cash')\" id=\"opt-cash\">\n");
      out.write("                <div class=\"pay-icon\">💵</div>\n");
      out.write("                <div class=\"pay-info\">\n");
      out.write("                    <strong>Cash on Delivery</strong>\n");
      out.write("                    <p style=\"font-size: 0.8rem; color: var(--text-muted)\">Pay when food arrives</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pay-check\" id=\"check-cash\">✓</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"payment-option\" onclick=\"selectPayment('upi')\" id=\"opt-upi\">\n");
      out.write("                <div class=\"pay-icon\">📱</div>\n");
      out.write("                <div class=\"pay-info\">\n");
      out.write("                    <strong>UPI Payment</strong>\n");
      out.write("                    <p style=\"font-size: 0.8rem; color: var(--text-muted)\">GPay, PhonePe, Paytm</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pay-check\" id=\"check-upi\" style=\"display:none;\">✓</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"payment-option\" onclick=\"selectPayment('card')\" id=\"opt-card\">\n");
      out.write("                <div class=\"pay-icon\">💳</div>\n");
      out.write("                <div class=\"pay-info\">\n");
      out.write("                    <strong>Card Payment</strong>\n");
      out.write("                    <p style=\"font-size: 0.8rem; color: var(--text-muted)\">Debit / Credit Card</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pay-check\" id=\"check-card\" style=\"display:none;\">✓</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- CASH DETAIL -->\n");
      out.write("        <div id=\"detail-cash\" class=\"payment-detail\">\n");
      out.write("            <div class=\"pay-detail-box\">\n");
      out.write("                <span style=\"font-size:2rem;\">🏍️</span>\n");
      out.write("                <div>\n");
      out.write("                    <strong>Pay on Delivery</strong>\n");
      out.write("                    <p style=\"font-size: 0.8rem;\">Keep <span id=\"cashAmt\" style=\"color:var(--primary);font-weight:700;\">Rs. 0.00</span> ready when delivery arrives</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- UPI DETAIL -->\n");
      out.write("        <div id=\"detail-upi\" class=\"payment-detail\" style=\"display:none;\">\n");
      out.write("            <div class=\"upi-box\">\n");
      out.write("                <div class=\"upi-qr\" style=\"flex: 1; text-align: center;\">\n");
      out.write("                    <div class=\"qr-placeholder\">\n");
      out.write("                        <span style=\"font-size:3rem;\">📱</span>\n");
      out.write("                        <p style=\"font-size: 0.8rem;\">Scan QR Code</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"upi-info\" style=\"flex: 2;\">\n");
      out.write("                    <p>UPI ID: <strong>benedictmart@upi</strong></p>\n");
      out.write("                    <p style=\"color:var(--text-muted);font-size:0.85rem;\">Pay <span id=\"upiAmt\" style=\"color:var(--primary);font-weight:700;\">Rs. 0.00</span> to complete</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\" style=\"margin-top:1rem;\">\n");
      out.write("                <label>Enter Transaction ID (optional)</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"e.g. GPay Ref: 123456\" id=\"upiTxnId\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- CARD DETAIL -->\n");
      out.write("        <div id=\"detail-card\" class=\"payment-detail\" style=\"display:none;\">\n");
      out.write("            <div class=\"card-preview\" id=\"cardPreview\">\n");
      out.write("                <div class=\"card-chip\">💳</div>\n");
      out.write("                <div class=\"card-num-preview\" id=\"cardNumPreview\" style=\"font-family: monospace; font-size: 1.1rem; margin: 0.5rem 0;\">•••• •••• •••• ••••</div>\n");
      out.write("                <div class=\"card-bottom\" style=\"display: flex; justify-content: space-between; font-size: 0.8rem; text-transform: uppercase;\">\n");
      out.write("                    <span id=\"cardNamePreview\">");
      out.print( firstName.toUpperCase() );
      out.write("</span>\n");
      out.write("                    <span id=\"cardExpPreview\">MM/YY</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Card Number</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"1234 5678 9012 3456\" maxlength=\"19\" id=\"cardNum\" oninput=\"formatCard(this)\">\n");
      out.write("            </div>\n");
      out.write("            <div style=\"display:grid;grid-template-columns:1fr 1fr;gap:1rem;\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>Expiry</label>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"MM/YY\" maxlength=\"5\" id=\"cardExp\" oninput=\"formatExpiry(this)\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>CVV</label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\" placeholder=\"•••\" maxlength=\"3\" id=\"cardCvv\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>Name on Card</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"");
      out.print( userName );
      out.write("\" id=\"cardName\" oninput=\"document.getElementById('cardNamePreview').textContent = this.value.toUpperCase() || '");
      out.print( firstName.toUpperCase() );
      out.write("'\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button onclick=\"confirmPayment()\" class=\"btn btn-primary\" id=\"confirmPayBtn\" style=\"margin-top: 1rem;\">✅ Confirm &amp; Place Order</button>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     SUCCESS OVERLAY\n");
      out.write("     ========================================================= -->\n");
      out.write("<div class=\"success-overlay\" id=\"successOverlay\">\n");
      out.write("    <div class=\"success-box\">\n");
      out.write("        <div class=\"success-icon\">🎉</div>\n");
      out.write("        <h2>Order Placed!</h2>\n");
      out.write("        <p id=\"successMsg\">Your order has been placed successfully!</p>\n");
      out.write("        <button onclick=\"closeSuccess()\" class=\"btn btn-primary\" style=\"width:auto;padding:0.75rem 2rem;margin-top:1rem;\">Continue Shopping</button>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- =========================================================\n");
      out.write("     JAVASCRIPT\n");
      out.write("     ========================================================= -->\n");
      out.write("<script>\n");
      out.write("const ctx = '");
      out.print( request.getContextPath() );
      out.write("';\n");
      out.write("let allItems = [];\n");
      out.write("let currentCategory = 'all';\n");
      out.write("let selectedPayment = 'cash';\n");
      out.write("let cartTotal = 0;\n");
      out.write("\n");
      out.write("const categoryImages = {\n");
      out.write("    'burger': 'https://pngimg.com/uploads/burger_sandwich/burger_sandwich_PNG4135.png',\n");
      out.write("    'pizza': 'https://pngimg.com/uploads/pizza/pizza_PNG44090.png',\n");
      out.write("    'biryani': 'https://pngimg.com/uploads/biryani/biryani_PNG28.png',\n");
      out.write("    'noodles': 'https://pngimg.com/uploads/noodle/noodle_PNG27.png',\n");
      out.write("    'salad': 'https://pngimg.com/uploads/salad/salad_PNG3656.png',\n");
      out.write("    'dessert': 'https://pngimg.com/uploads/cake/cake_PNG13122.png',\n");
      out.write("    'drink': 'https://pngimg.com/uploads/coca_cola/coca_cola_PNG8911.png',\n");
      out.write("    'starter': 'https://pngimg.com/uploads/samosa/samosa_PNG12.png',\n");
      out.write("    'mains': 'https://pngimg.com/uploads/curry/curry_PNG21.png',\n");
      out.write("    'south indian': 'https://pngimg.com/uploads/dosa/dosa_PNG15.png',\n");
      out.write("    'north indian': 'https://pngimg.com/uploads/paneer/paneer_PNG18.png',\n");
      out.write("    'chinese': 'https://pngimg.com/uploads/dumplings/dumplings_PNG12.png',\n");
      out.write("    'italian': 'https://pngimg.com/uploads/pasta/pasta_PNG56.png',\n");
      out.write("    'sandwich': 'https://pngimg.com/uploads/sandwich/sandwich_PNG62.png',\n");
      out.write("    'default': 'https://pngimg.com/uploads/burger_sandwich/burger_sandwich_PNG4135.png'\n");
      out.write("};\n");
      out.write("\n");
      out.write("const categoryIcons = {\n");
      out.write("    'burger': '🍔', 'pizza': '🍕', 'biryani': '🍛', 'noodles': '🍜', 'salad': '🥗',\n");
      out.write("    'dessert': '🍰', 'desserts': '🍰', 'drink': '🥤', 'drinks': '🥤',\n");
      out.write("    'starter': '🥟', 'starters': '🥟', 'mains': '🍛', 'main': '🍛', 'burgers': '🍔',\n");
      out.write("    'south indian': '🥘', 'north indian': '🍲', 'chinese': '🥡', 'italian': '🍝',\n");
      out.write("    'seafood': '🦐', 'sandwich': '🥪', 'sandwiches': '🥪', 'default': '🍽️'\n");
      out.write("};\n");
      out.write("\n");
      out.write("function getImage(item) {\n");
      out.write("    if (item.imageUrl && item.imageUrl.endsWith('.png')) return item.imageUrl;\n");
      out.write("    const cat = (item.category || '').toLowerCase();\n");
      out.write("    for (const key of Object.keys(categoryImages)) {\n");
      out.write("        if (cat.includes(key)) return categoryImages[key];\n");
      out.write("    }\n");
      out.write("    return categoryImages['default'];\n");
      out.write("}\n");
      out.write("\n");
      out.write("function getIcon(cat) {\n");
      out.write("    if (!cat) return '🍽️';\n");
      out.write("    const c = cat.toLowerCase();\n");
      out.write("    return categoryIcons[c] || categoryIcons[c.replace(/s$/, '')] || '🍽️';\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function loadMenu() {\n");
      out.write("    try {\n");
      out.write("        const res = await fetch(ctx + '/api/v1/menu-items');\n");
      out.write("        if (!res.ok) throw new Error('HTTP ' + res.status);\n");
      out.write("        const result = await res.json();\n");
      out.write("        if (!result.data) throw new Error('No data');\n");
      out.write("        allItems = result.data;\n");
      out.write("        buildCategoryTabs(allItems);\n");
      out.write("        renderMenu(allItems);\n");
      out.write("    } catch (err) {\n");
      out.write("        console.error(\"Failed to load menu\", err);\n");
      out.write("        document.getElementById('menuList').innerHTML = '<p style=\"color:var(--text-muted);grid-column:1/-1;text-align:center;padding:2rem;\">⚠️ Could not load menu. Please refresh.</p>';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function askAI() {\n");
      out.write("    const q = document.getElementById('aiQuery').value.trim().toLowerCase();\n");
      out.write("    if (!q) return;\n");
      out.write("    document.getElementById('sectionEmoji').textContent = '✨';\n");
      out.write("    document.getElementById('sectionLabel').textContent = 'AI Curated Recommendations';\n");
      out.write("    \n");
      out.write("    const filtered = allItems.filter(item => {\n");
      out.write("        const nameMatch = item.name.toLowerCase().includes(q);\n");
      out.write("        const descMatch = item.description && item.description.toLowerCase().includes(q);\n");
      out.write("        const catMatch = item.category && item.category.toLowerCase().includes(q);\n");
      out.write("        let priceMatch = true;\n");
      out.write("        if (q.includes('250') || q.includes('under 250')) priceMatch = item.price <= 250;\n");
      out.write("        if (q.includes('200') || q.includes('under 200')) priceMatch = item.price <= 200;\n");
      out.write("        return (nameMatch || descMatch || catMatch) && priceMatch;\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    renderMenu(filtered.length ? filtered : allItems);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function quickSearch(prompt) {\n");
      out.write("    document.getElementById('aiQuery').value = prompt;\n");
      out.write("    askAI();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function buildCategoryTabs(items) {\n");
      out.write("    const cats = [...new Set(items.map(i => i.category).filter(Boolean))];\n");
      out.write("    const container = document.getElementById('categoryTabs');\n");
      out.write("    cats.forEach(cat => {\n");
      out.write("        const btn = document.createElement('button');\n");
      out.write("        btn.className = 'category-tab';\n");
      out.write("        btn.dataset.cat = cat;\n");
      out.write("        btn.onclick = () => filterByCategory(cat);\n");
      out.write("        btn.innerHTML = getIcon(cat) + ' ' + cat;\n");
      out.write("        container.appendChild(btn);\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function filterByCategory(cat) {\n");
      out.write("    currentCategory = cat;\n");
      out.write("    document.querySelectorAll('.category-tab').forEach(b => b.classList.toggle('active', b.dataset.cat === cat));\n");
      out.write("    const filtered = cat === 'all' ? allItems : allItems.filter(i => i.category === cat);\n");
      out.write("    document.getElementById('sectionEmoji').textContent = cat === 'all' ? '🔥' : getIcon(cat);\n");
      out.write("    document.getElementById('sectionLabel').textContent = cat === 'all' ? 'Explore Delicious Menu' : cat;\n");
      out.write("    renderMenu(filtered);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function renderMenu(items) {\n");
      out.write("    const container = document.getElementById('menuList');\n");
      out.write("    container.innerHTML = '';\n");
      out.write("    \n");
      out.write("    if (!items || items.length === 0) {\n");
      out.write("        container.innerHTML = '<p style=\"color:var(--text-muted);grid-column:1/-1;text-align:center;padding:2rem;\">No items match your query.</p>';\n");
      out.write("        return;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    items.forEach(item => {\n");
      out.write("        const img = getImage(item);\n");
      out.write("        const card = document.createElement('div');\n");
      out.write("        card.className = 'menu-card';\n");
      out.write("        \n");
      out.write("        card.innerHTML = \n");
      out.write("            '<div class=\"food-image-wrap\">' +\n");
      out.write("                '<img src=\"' + img + '\" alt=\"' + item.name + '\" class=\"food-image\">' +\n");
      out.write("                (item.category ? '<span class=\"category-badge\">' + getIcon(item.category) + ' ' + item.category + '</span>' : '') +\n");
      out.write("            '</div>' +\n");
      out.write("            '<div class=\"menu-card-body\">' +\n");
      out.write("                '<div class=\"menu-card-header\">' +\n");
      out.write("                    '<span class=\"item-name\">' + item.name + '</span>' +\n");
      out.write("                    '<span class=\"item-price\">Rs.' + parseFloat(item.price).toFixed(0) + '</span>' +\n");
      out.write("                '</div>' +\n");
      out.write("                (item.description ? '<p class=\"item-desc\">' + item.description + '</p>' : '') +\n");
      out.write("                '<button onclick=\"addToCart(' + item.id + ', this)\" class=\"btn-add\">+ Add to Cart</button>' +\n");
      out.write("            '</div>';\n");
      out.write("        \n");
      out.write("        container.appendChild(card);\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function addToCart(menuItemId, btn) {\n");
      out.write("    btn.disabled = true;\n");
      out.write("    btn.textContent = 'Adding...';\n");
      out.write("    const formData = new URLSearchParams();\n");
      out.write("    formData.append('menuItemId', menuItemId);\n");
      out.write("    formData.append('quantity', 1);\n");
      out.write("    \n");
      out.write("    try {\n");
      out.write("        await fetch(ctx + '/api/v1/cart', { method: 'POST', body: formData });\n");
      out.write("        await loadCart();\n");
      out.write("        btn.textContent = '✓ Added!';\n");
      out.write("        btn.style.background = '#16a34a';\n");
      out.write("        btn.style.color = '#fff';\n");
      out.write("        btn.style.borderColor = '#16a34a';\n");
      out.write("        setTimeout(() => {\n");
      out.write("            btn.disabled = false;\n");
      out.write("            btn.textContent = '+ Add to Cart';\n");
      out.write("            btn.style.background = '';\n");
      out.write("            btn.style.color = '';\n");
      out.write("            btn.style.borderColor = '';\n");
      out.write("        }, 1500);\n");
      out.write("    } catch (e) {\n");
      out.write("        btn.disabled = false;\n");
      out.write("        btn.textContent = '+ Add to Cart';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function loadCart() {\n");
      out.write("    try {\n");
      out.write("        const res = await fetch(ctx + '/api/v1/cart');\n");
      out.write("        const result = await res.json();\n");
      out.write("        const cartContainer = document.getElementById('cartItems');\n");
      out.write("        const payBtn = document.getElementById('payBtn');\n");
      out.write("        const cartSummary = document.getElementById('cartSummary');\n");
      out.write("        const cartBadge = document.getElementById('cartBadge');\n");
      out.write("        \n");
      out.write("        cartContainer.innerHTML = '';\n");
      out.write("        \n");
      out.write("        if (!result.data || !result.data.items || result.data.items.length === 0) {\n");
      out.write("            cartContainer.innerHTML = \n");
      out.write("                '<div class=\"empty-cart-msg\">' +\n");
      out.write("                    '<span style=\"font-size:2.5rem;\">🛒</span>' +\n");
      out.write("                    '<p>Your cart is empty</p>' +\n");
      out.write("                    '<small>Add items from the menu</small>' +\n");
      out.write("                '</div>';\n");
      out.write("            cartSummary.style.display = 'none';\n");
      out.write("            payBtn.disabled = true;\n");
      out.write("            cartBadge.style.display = 'none';\n");
      out.write("            cartTotal = 0;\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        let subtotal = 0;\n");
      out.write("        let itemCount = 0;\n");
      out.write("        \n");
      out.write("        result.data.items.forEach(item => {\n");
      out.write("            const lineTotal = parseFloat(item.price) * item.quantity;\n");
      out.write("            subtotal += lineTotal;\n");
      out.write("            itemCount += item.quantity;\n");
      out.write("            \n");
      out.write("            const div = document.createElement('div');\n");
      out.write("            div.className = 'cart-item';\n");
      out.write("            div.innerHTML = \n");
      out.write("                '<div>' +\n");
      out.write("                    '<strong style=\"display:block;font-size:0.9rem;\">' + item.name + '</strong>' +\n");
      out.write("                    '<span style=\"font-size:0.78rem;color:var(--text-muted);\">Rs.' + parseFloat(item.price).toFixed(0) + ' &times; ' + item.quantity + '</span>' +\n");
      out.write("                '</div>' +\n");
      out.write("                '<span style=\"font-weight:700;color:var(--primary);\">Rs.' + lineTotal.toFixed(0) + '</span>';\n");
      out.write("            cartContainer.appendChild(div);\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        const tax = subtotal * 0.05;\n");
      out.write("        cartTotal = subtotal + tax;\n");
      out.write("        \n");
      out.write("        document.getElementById('cartSubtotal').textContent = 'Rs. ' + subtotal.toFixed(2);\n");
      out.write("        document.getElementById('cartTax').textContent = 'Rs. ' + tax.toFixed(2);\n");
      out.write("        document.getElementById('cartTotal').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("        document.getElementById('modalTotal').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("        document.getElementById('cashAmt').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("        document.getElementById('upiAmt').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("        \n");
      out.write("        cartBadge.textContent = itemCount;\n");
      out.write("        cartBadge.style.display = 'inline-block';\n");
      out.write("        cartSummary.style.display = 'block';\n");
      out.write("        payBtn.disabled = false;\n");
      out.write("    } catch (err) {\n");
      out.write("        console.error(\"Failed to load cart\", err);\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function openPayment() {\n");
      out.write("    document.getElementById('paymentModal').classList.add('active');\n");
      out.write("    document.getElementById('modalTotal').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("    document.getElementById('cashAmt').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("    document.getElementById('upiAmt').textContent = 'Rs. ' + cartTotal.toFixed(2);\n");
      out.write("    selectPayment('cash');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function closePayment() {\n");
      out.write("    document.getElementById('paymentModal').classList.remove('active');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function selectPayment(type) {\n");
      out.write("    selectedPayment = type;\n");
      out.write("    ['cash', 'upi', 'card'].forEach(t => {\n");
      out.write("        const opt = document.getElementById('opt-' + t);\n");
      out.write("        const chk = document.getElementById('check-' + t);\n");
      out.write("        const det = document.getElementById('detail-' + t);\n");
      out.write("        const sel = t === type;\n");
      out.write("        opt.classList.toggle('selected', sel);\n");
      out.write("        chk.style.display = sel ? 'block' : 'none';\n");
      out.write("        det.style.display = sel ? 'block' : 'none';\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function confirmPayment() {\n");
      out.write("    const btn = document.getElementById('confirmPayBtn');\n");
      out.write("    btn.disabled = true;\n");
      out.write("    btn.textContent = 'Processing...';\n");
      out.write("    \n");
      out.write("    try {\n");
      out.write("        const res = await fetch(ctx + '/api/v1/orders', { method: 'POST' });\n");
      out.write("        const result = await res.json();\n");
      out.write("        closePayment();\n");
      out.write("        \n");
      out.write("        if (result.success) {\n");
      out.write("            const payLabel = { cash: 'Cash on Delivery', upi: 'UPI', card: 'Card Payment' }[selectedPayment];\n");
      out.write("            document.getElementById('successMsg').innerHTML = \n");
      out.write("                'Order <strong>#' + result.data.orderId + '</strong> confirmed!<br>' +\n");
      out.write("                '<small style=\"display:block;margin-top:0.5rem;color:var(--text-muted)\">Payment: ' + payLabel + ' | Total: Rs.' + cartTotal.toFixed(2) + '</small>';\n");
      out.write("            document.getElementById('successOverlay').classList.add('active');\n");
      out.write("            loadCart();\n");
      out.write("        } else {\n");
      out.write("            const msg = document.getElementById('message');\n");
      out.write("            msg.className = 'alert-message alert-error';\n");
      out.write("            msg.textContent = (result.error && result.error.message) || 'Could not place order';\n");
      out.write("        }\n");
      out.write("    } catch (err) {\n");
      out.write("        closePayment();\n");
      out.write("        const msg = document.getElementById('message');\n");
      out.write("        msg.className = 'alert-message alert-error';\n");
      out.write("        msg.textContent = 'Connection failed. Please try again.';\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    btn.disabled = false;\n");
      out.write("    btn.innerHTML = '✅ Confirm &amp; Place Order';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function closeSuccess() {\n");
      out.write("    document.getElementById('successOverlay').classList.remove('active');\n");
      out.write("}\n");
      out.write("\n");
      out.write("async function doLogout() {\n");
      out.write("    try { await fetch(ctx + '/api/v1/logout', { method: 'POST' }); } catch (e) { console.error('Logout request failed', e); }\n");
      out.write("    window.location.href = ctx + '/login.jsp';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function formatCard(input) {\n");
      out.write("    let v = input.value.replace(/\\D/g, '').substring(0, 16);\n");
      out.write("    input.value = (v.match(/.{1,4}/g) || []).join(' ') || v;\n");
      out.write("    const padded = (v + '••••••••••••••••').substring(0, 16).match(/.{1,4}/g);\n");
      out.write("    document.getElementById('cardNumPreview').textContent = padded.join(' ');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function formatExpiry(input) {\n");
      out.write("    let v = input.value.replace(/\\D/g, '').substring(0, 4);\n");
      out.write("    if (v.length >= 2) v = v.substring(0, 2) + '/' + v.substring(2);\n");
      out.write("    input.value = v;\n");
      out.write("    document.getElementById('cardExpPreview').textContent = v || 'MM/YY';\n");
      out.write("}\n");
      out.write("\n");
      out.write("document.getElementById('paymentModal').addEventListener('click', function(e) {\n");
      out.write("    if (e.target === this) closePayment();\n");
      out.write("});\n");
      out.write("\n");
      out.write("setTimeout(function() {\n");
      out.write("    const toast = document.getElementById('welcomeToast');\n");
      out.write("    if (toast) {\n");
      out.write("        toast.classList.add('hide');\n");
      out.write("        setTimeout(() => toast.remove(), 450);\n");
      out.write("    }\n");
      out.write("}, 4000);\n");
      out.write("\n");
      out.write("loadMenu();\n");
      out.write("loadCart();\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
