/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-09-20 15:41:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login - BenedictJeromeMart</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header class=\"navbar\">\n");
      out.write("        <a href=\"#\" class=\"brand\">\n");
      out.write("            <div class=\"brand-icon\">🛒</div>\n");
      out.write("            BenedictJeromeMart\n");
      out.write("        </a>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <main class=\"auth-container\">\n");
      out.write("        <div class=\"auth-card\">\n");
      out.write("            <div class=\"auth-header\">\n");
      out.write("                <h2>Welcome Back!</h2>\n");
      out.write("                <p style=\"color:var(--text-muted)\">Log in to order your favorite delicious food</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form id=\"loginForm\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">Email Address</label>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"name@example.com\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\">Password</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"••••••••\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\" style=\"margin-top: 1rem;\">\n");
      out.write("                    Sign In ➔\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div id=\"message\"></div>\n");
      out.write("\n");
      out.write("            <div class=\"auth-footer\">\n");
      out.write("                Don't have an account yet? <a href=\"register.jsp\" style=\"color:var(--primary);font-weight:bold;\">Create one here</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        document.getElementById('loginForm').addEventListener('submit', async function(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            const messageDiv = document.getElementById('message');\n");
      out.write("            messageDiv.innerHTML = '';\n");
      out.write("            \n");
      out.write("            const formData = new URLSearchParams(new FormData(this));\n");
      out.write("\n");
      out.write("            try {\n");
      out.write("                const response = await fetch('");
      out.print( request.getContextPath() );
      out.write("/api/v1/login', {\n");
      out.write("                    method: 'POST',\n");
      out.write("                    body: formData\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                const result = await response.json();\n");
      out.write("                if (result.success) {\n");
      out.write("                    messageDiv.className = 'alert-message alert-success';\n");
      out.write("                    messageDiv.textContent = 'Login successful! Redirecting...';\n");
      out.write("                    setTimeout(() => {\n");
      out.write("                        window.location.href = 'home.jsp';\n");
      out.write("                    }, 500);\n");
      out.write("                } else {\n");
      out.write("                    messageDiv.className = 'alert-message alert-error';\n");
      out.write("                    messageDiv.textContent = result.error.message || 'Invalid credentials';\n");
      out.write("                }\n");
      out.write("            } catch (err) {\n");
      out.write("                messageDiv.className = 'alert-message alert-error';\n");
      out.write("                messageDiv.textContent = 'Server connection error. Please try again.';\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
