/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-09-20 15:48:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manage_002dmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String userName = (String) session.getAttribute("userName");
    String userRole = (String) session.getAttribute("userRole");
    if (userName == null || userName.isEmpty()) userName = "Guest";
    String firstName = userName.contains(" ") ? userName.split(" ")[0] : userName;

    // Only restaurant owners may access this page.
    if (!"RESTAURANT_OWNER".equals(userRole)) {
        response.sendRedirect(request.getContextPath() + "/home.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Manage Menu - BenedictJeromeMart</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Flat Layout Extentions for Management UI */\r\n");
      out.write("        .manage-layout { max-width: 1200px; margin: 1.5rem auto; padding: 0 1rem; display: grid; grid-template-columns: 360px 1fr; gap: 1.5rem; }\r\n");
      out.write("        @media (max-width: 900px) { .manage-layout { grid-template-columns: 1fr; } }\r\n");
      out.write("        .manage-panel { background: var(--bg-card); border-radius: 8px; border: 1px solid var(--border); padding: 1.5rem; }\r\n");
      out.write("        .manage-panel h2 { margin-bottom: 1rem; font-size: 1.2rem; }\r\n");
      out.write("        .seed-bar { display: flex; align-items: center; justify-content: space-between; gap: 1rem; margin-bottom: 1rem; flex-wrap: wrap; }\r\n");
      out.write("        .dish-table-wrap { overflow-x: auto; }\r\n");
      out.write("        table.dish-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }\r\n");
      out.write("        table.dish-table th, table.dish-table td { text-align: left; padding: 0.75rem 0.6rem; border-bottom: 1px solid var(--border); vertical-align: middle; }\r\n");
      out.write("        table.dish-table img { width: 42px; height: 42px; object-fit: cover; border-radius: 4px; border: 1px solid var(--border); }\r\n");
      out.write("        table.dish-table .row-actions { display: flex; gap: 0.4rem; }\r\n");
      out.write("        .btn-tiny { padding: 0.3rem 0.6rem; font-size: 0.8rem; border-radius: 4px; border: none; cursor: pointer; font-weight: bold; }\r\n");
      out.write("        .btn-tiny.edit { background: #e0e7ff; color: #3730a3; }\r\n");
      out.write("        .btn-tiny.delete { background: #fee2e2; color: #b91c1c; }\r\n");
      out.write("        #seedProgress { font-size: 0.85rem; color: var(--text-muted); margin-top: 0.4rem; }\r\n");
      out.write("        .stock-low { color: #b91c1c; font-weight: 700; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"navbar\">\r\n");
      out.write("    <a href=\"home.jsp\" class=\"brand\">\r\n");
      out.write("        <div class=\"brand-icon\">🛒</div>\r\n");
      out.write("        BenedictJeromeMart\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"nav-right\">\r\n");
      out.write("        <a href=\"home.jsp\" class=\"btn btn-outline-sm\">Home</a>\r\n");
      out.write("        <div class=\"welcome-badge\">\r\n");
      out.write("            <span class=\"welcome-avatar\">");
      out.print( firstName.charAt(0) );
      out.write("</span>\r\n");
      out.write("            Hey, <strong>");
      out.print( firstName );
      out.write("</strong>! 👋\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"#\" onclick=\"doLogout(); return false;\" class=\"btn btn-outline-sm\">🚪 Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main class=\"manage-layout\">\r\n");
      out.write("    <!-- ===== ADD / EDIT FORM ===== -->\r\n");
      out.write("    <section class=\"manage-panel\">\r\n");
      out.write("        <h2 id=\"formTitle\">➕ Add a Dish</h2>\r\n");
      out.write("        <form id=\"dishForm\" onsubmit=\"return submitDish(event)\">\r\n");
      out.write("            <input type=\"hidden\" id=\"dishId\" value=\"\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Name</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"dishName\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Description</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"dishDesc\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"display:grid;grid-template-columns:1fr 1fr;gap:1rem;\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Price (Rs.)</label>\r\n");
      out.write("                    <input type=\"number\" step=\"0.01\" min=\"0\" class=\"form-control\" id=\"dishPrice\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Stock Qty</label>\r\n");
      out.write("                    <input type=\"number\" min=\"0\" class=\"form-control\" id=\"dishStock\" value=\"20\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Category</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"dishCategory\" placeholder=\"e.g. Biryani, Pizza, Dessert\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Image URL (optional)</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"dishImage\" maxlength=\"500\" placeholder=\"https://example.com/photo.jpg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\" id=\"dishSubmitBtn\">Add Dish</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-sm\" id=\"cancelEditBtn\" onclick=\"resetForm()\" style=\"display:none;margin-top:0.5rem;width:100%;\">Cancel Edit</button>\r\n");
      out.write("            <div id=\"formMessage\"></div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- ===== DISH LIST ===== -->\r\n");
      out.write("    <section class=\"manage-panel\">\r\n");
      out.write("        <div class=\"seed-bar\">\r\n");
      out.write("            <h2 style=\"margin:0;\">🍽️ Your Dishes (<span id=\"dishCount\">0</span>)</h2>\r\n");
      out.write("            <div>\r\n");
      out.write("                <button class=\"btn btn-outline-sm\" onclick=\"seedDishes()\" id=\"seedBtn\">⚡ Seed 100 Sample Dishes</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"seedProgress\"></div>\r\n");
      out.write("        <div class=\"dish-table-wrap\">\r\n");
      out.write("            <table class=\"dish-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"dishTableBody\">\r\n");
      out.write("                    <tr><td colspan=\"6\" style=\"text-align:center;padding:1.5rem;\">Loading...</td></tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const ctx = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("let restaurantId = null;\r\n");
      out.write("let allDishes = [];\r\n");
      out.write("\r\n");
      out.write("const categoryImages = {\r\n");
      out.write("    'burger':  'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&q=80',\r\n");
      out.write("    'pizza':   'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&q=80',\r\n");
      out.write("    'biryani': 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=300&q=80',\r\n");
      out.write("    'noodles': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300&q=80',\r\n");
      out.write("    'salad':   'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&q=80',\r\n");
      out.write("    'dessert': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=300&q=80',\r\n");
      out.write("    'drink':   'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=300&q=80',\r\n");
      out.write("    'starter': 'https://images.unsplash.com/photo-1617622141675-d3005b9d5e8a?w=300&q=80',\r\n");
      out.write("    'mains':   'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=300&q=80',\r\n");
      out.write("    'south indian': 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=300&q=80',\r\n");
      out.write("    'north indian': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300&q=80',\r\n");
      out.write("    'chinese': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=300&q=80',\r\n");
      out.write("    'italian': 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?w=300&q=80',\r\n");
      out.write("    'seafood': 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=300&q=80',\r\n");
      out.write("    'sandwich': 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=300&q=80',\r\n");
      out.write("    'default': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300&q=80'\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function imageFor(category) {\r\n");
      out.write("    const c = (category || '').toLowerCase();\r\n");
      out.write("    for (const key of Object.keys(categoryImages)) {\r\n");
      out.write("        if (c.includes(key)) return categoryImages[key];\r\n");
      out.write("    }\r\n");
      out.write("    return categoryImages['default'];\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("async function loadDishes() {\r\n");
      out.write("    try {\r\n");
      out.write("        const res = await fetch(ctx + '/api/v1/owner/menu-items');\r\n");
      out.write("        const result = await res.json();\r\n");
      out.write("        if (!result.success) {\r\n");
      out.write("            document.getElementById('dishTableBody').innerHTML =\r\n");
      out.write("                '<tr><td colspan=\"6\" style=\"text-align:center;padding:1.5rem;\">' + (result.error ? result.error.message : 'Could not load dishes') + '</td></tr>';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        restaurantId = result.data.restaurantId;\r\n");
      out.write("        allDishes = result.data.items || [];\r\n");
      out.write("        renderDishes();\r\n");
      out.write("    } catch (err) {\r\n");
      out.write("        console.error('Failed to load dishes', err);\r\n");
      out.write("        document.getElementById('dishTableBody').innerHTML = '<tr><td colspan=\"6\" style=\"text-align:center;padding:1.5rem;\">⚠️ Could not load dishes. Please refresh.</td></tr>';\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function renderDishes() {\r\n");
      out.write("    document.getElementById('dishCount').textContent = allDishes.length;\r\n");
      out.write("    const body = document.getElementById('dishTableBody');\r\n");
      out.write("    if (allDishes.length === 0) {\r\n");
      out.write("        body.innerHTML = '<tr><td colspan=\"6\" style=\"text-align:center;padding:1.5rem;\">No dishes yet. Add one, or seed 100 sample dishes.</td></tr>';\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    body.innerHTML = allDishes.map(d => {\r\n");
      out.write("        const img = (d.imageUrl && d.imageUrl.startsWith('http')) ? d.imageUrl : imageFor(d.category);\r\n");
      out.write("        const stockClass = d.stockQty <= 0 ? 'stock-low' : '';\r\n");
      out.write("        return '<tr>' +\r\n");
      out.write("            '<td><img src=\"' + img + '\" alt=\"' + escapeHtml(d.name) + '\" onerror=\"this.src=\\'' + categoryImages['default'] + '\\';\"></td>' +\r\n");
      out.write("            '<td>' + escapeHtml(d.name) + '<br><small style=\"color:var(--text-muted);\">' + escapeHtml(d.description || '') + '</small></td>' +\r\n");
      out.write("            '<td>' + escapeHtml(d.category || '') + '</td>' +\r\n");
      out.write("            '<td>Rs.' + Number(d.price).toFixed(0) + '</td>' +\r\n");
      out.write("            '<td class=\"' + stockClass + '\">' + d.stockQty + '</td>' +\r\n");
      out.write("            '<td class=\"row-actions\">' +\r\n");
      out.write("                '<button class=\"btn-tiny edit\" onclick=\"editDish(' + d.id + ')\">Edit</button>' +\r\n");
      out.write("                '<button class=\"btn-tiny delete\" onclick=\"deleteDish(' + d.id + ')\">Delete</button>' +\r\n");
      out.write("            '</td>' +\r\n");
      out.write("        '</tr>';\r\n");
      out.write("    }).join('');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function escapeHtml(s) {\r\n");
      out.write("    return (s || '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function editDish(id) {\r\n");
      out.write("    const d = allDishes.find(x => x.id === id);\r\n");
      out.write("    if (!d) return;\r\n");
      out.write("    document.getElementById('formTitle').textContent = '✏️ Edit Dish';\r\n");
      out.write("    document.getElementById('dishId').value = d.id;\r\n");
      out.write("    document.getElementById('dishName').value = d.name || '';\r\n");
      out.write("    document.getElementById('dishDesc').value = d.description || '';\r\n");
      out.write("    document.getElementById('dishPrice').value = d.price;\r\n");
      out.write("    document.getElementById('dishStock').value = d.stockQty;\r\n");
      out.write("    document.getElementById('dishCategory').value = d.category || '';\r\n");
      out.write("    document.getElementById('dishImage').value = d.imageUrl || '';\r\n");
      out.write("    document.getElementById('dishSubmitBtn').textContent = 'Save Changes';\r\n");
      out.write("    document.getElementById('cancelEditBtn').style.display = 'inline-block';\r\n");
      out.write("    window.scrollTo({top: 0, behavior: 'smooth'});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetForm() {\r\n");
      out.write("    document.getElementById('formTitle').textContent = '➕ Add a Dish';\r\n");
      out.write("    document.getElementById('dishForm').reset();\r\n");
      out.write("    document.getElementById('dishId').value = '';\r\n");
      out.write("    document.getElementById('dishStock').value = 20;\r\n");
      out.write("    document.getElementById('dishSubmitBtn').textContent = 'Add Dish';\r\n");
      out.write("    document.getElementById('cancelEditBtn').style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("async function submitDish(evt) {\r\n");
      out.write("    evt.preventDefault();\r\n");
      out.write("    const id = document.getElementById('dishId').value;\r\n");
      out.write("    const body = new URLSearchParams();\r\n");
      out.write("    if (id) body.append('id', id);\r\n");
      out.write("    body.append('name', document.getElementById('dishName').value);\r\n");
      out.write("    body.append('description', document.getElementById('dishDesc').value);\r\n");
      out.write("    body.append('price', document.getElementById('dishPrice').value);\r\n");
      out.write("    body.append('stockQty', document.getElementById('dishStock').value);\r\n");
      out.write("    body.append('category', document.getElementById('dishCategory').value);\r\n");
      out.write("    body.append('imageUrl', document.getElementById('dishImage').value);\r\n");
      out.write("\r\n");
      out.write("    const msg = document.getElementById('formMessage');\r\n");
      out.write("    try {\r\n");
      out.write("        const res = await fetch(ctx + '/api/v1/owner/menu-items', { method: 'POST', body: body });\r\n");
      out.write("        const result = await res.json();\r\n");
      out.write("        if (result.success) {\r\n");
      out.write("            msg.className = 'alert-message alert-success';\r\n");
      out.write("            msg.textContent = id ? 'Dish updated!' : 'Dish added!';\r\n");
      out.write("            resetForm();\r\n");
      out.write("            await loadDishes();\r\n");
      out.write("        } else {\r\n");
      out.write("            msg.className = 'alert-message alert-error';\r\n");
      out.write("            msg.textContent = (result.error && result.error.message) || 'Could not save dish';\r\n");
      out.write("        }\r\n");
      out.write("    } catch (err) {\r\n");
      out.write("        msg.className = 'alert-message alert-error';\r\n");
      out.write("        msg.textContent = 'Connection failed. Please try again.';\r\n");
      out.write("    }\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("async function deleteDish(id) {\r\n");
      out.write("    if (!confirm('Delete this dish?')) return;\r\n");
      out.write("    try {\r\n");
      out.write("        await fetch(ctx + '/api/v1/owner/menu-items?id=' + id, { method: 'DELETE' });\r\n");
      out.write("        await loadDishes();\r\n");
      out.write("    } catch (err) {\r\n");
      out.write("        console.error('Failed to delete dish', err);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const seedCategories = {\r\n");
      out.write("    'Burger':  ['Classic Cheese Burger','Double Patty Burger','Veggie Burger','Spicy Chicken Burger','Mushroom Swiss Burger','BBQ Bacon Burger','Paneer Tikka Burger'],\r\n");
      out.write("    'Pizza':   ['Margherita Pizza','Pepperoni Pizza','Farmhouse Pizza','BBQ Chicken Pizza','Paneer Tikka Pizza','Four Cheese Pizza','Veggie Supreme Pizza'],\r\n");
      out.write("    'Biryani': ['Chicken Biryani','Mutton Biryani','Veg Biryani','Egg Biryani','Prawn Biryani','Hyderabadi Biryani','Paneer Biryani'],\r\n");
      out.write("    'Noodles': ['Hakka Noodles','Schezwan Noodles','Chicken Noodles','Veg Fried Noodles','Singapore Noodles','Egg Noodles','Thai Noodles'],\r\n");
      out.write("    'Salad':   ['Caesar Salad','Greek Salad','Fruit Salad','Sprouts Salad','Chicken Salad','Quinoa Salad','Garden Salad'],\r\n");
      out.write("    'Dessert': ['Chocolate Brownie','Gulab Jamun','Ice Cream Sundae','Cheesecake','Rasmalai','Tiramisu','Fruit Custard'],\r\n");
      out.write("    'Drink':   ['Cold Coffee','Fresh Lime Soda','Mango Lassi','Iced Tea','Chocolate Shake','Masala Chaas','Watermelon Juice'],\r\n");
      out.write("    'Starters': ['Paneer Tikka','Chicken 65','Spring Rolls','Veg Manchurian','Chilli Chicken','Corn Cheese Balls','Fish Fingers'],\r\n");
      out.write("    'South Indian': ['Masala Dosa','Idli Sambar','Uttapam','Medu Vada','Rava Dosa','Pongal','Curd Rice'],\r\n");
      out.write("    'North Indian': ['Butter Chicken','Paneer Butter Masala','Dal Makhani','Chole Bhature','Rajma Chawal','Aloo Paratha','Kadai Paneer'],\r\n");
      out.write("    'Chinese': ['Veg Manchurian','Chilli Paneer','Spring Rolls','Fried Rice','Sweet Corn Soup','Honey Chilli Potato','Kung Pao Chicken'],\r\n");
      out.write("    'Italian': ['Spaghetti Aglio Olio','Penne Arrabbiata','Lasagna','Risotto','Fettuccine Alfredo','Bruschetta','Minestrone Soup'],\r\n");
      out.write("    'Seafood': ['Grilled Fish','Prawn Curry','Fish Tikka','Fish and Chips','Prawn Tempura','Crab Curry','Fish Curry'],\r\n");
      out.write("    'Sandwich': ['Club Sandwich','Grilled Cheese Sandwich','Veg Sandwich','Chicken Sandwich','Paneer Sandwich','Egg Sandwich','Bombay Sandwich']\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function buildSeedList() {\r\n");
      out.write("    const list = [];\r\n");
      out.write("    for (const [cat, names] of Object.entries(seedCategories)) {\r\n");
      out.write("        names.forEach(name => {\r\n");
      out.write("            list.push({\r\n");
      out.write("                name: name,\r\n");
      out.write("                description: 'Freshly prepared ' + name.toLowerCase() + ', made to order.',\r\n");
      out.write("                price: (99 + Math.floor(Math.random() * 300)),\r\n");
      out.write("                stockQty: 15 + Math.floor(Math.random() * 30),\r\n");
      out.write("                category: cat,\r\n");
      out.write("                imageUrl: imageFor(cat)\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    list.push({ name: 'Chef Special Combo', description: 'A curated combo picked by the chef.', price: 249, stockQty: 25, category: 'Mains', imageUrl: imageFor('mains') });\r\n");
      out.write("    list.push({ name: 'Kids Meal Combo', description: 'A fun, kid-friendly combo meal.', price: 179, stockQty: 25, category: 'Mains', imageUrl: imageFor('mains') });\r\n");
      out.write("    return list;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("async function seedDishes() {\r\n");
      out.write("    if (!confirm('This will add 100 sample dishes to your menu. Continue?')) return;\r\n");
      out.write("    const seedBtn = document.getElementById('seedBtn');\r\n");
      out.write("    const progress = document.getElementById('seedProgress');\r\n");
      out.write("    seedBtn.disabled = true;\r\n");
      out.write("    const items = buildSeedList();\r\n");
      out.write("    let done = 0;\r\n");
      out.write("    const batchSize = 8;\r\n");
      out.write("\r\n");
      out.write("    for (let i = 0; i < items.length; i += batchSize) {\r\n");
      out.write("        const batch = items.slice(i, i + batchSize);\r\n");
      out.write("        await Promise.all(batch.map(item => {\r\n");
      out.write("            const body = new URLSearchParams();\r\n");
      out.write("            body.append('name', item.name);\r\n");
      out.write("            body.append('description', item.description);\r\n");
      out.write("            body.append('price', item.price);\r\n");
      out.write("            body.append('stockQty', item.stockQty);\r\n");
      out.write("            body.append('category', item.category);\r\n");
      out.write("            body.append('imageUrl', item.imageUrl);\r\n");
      out.write("            return fetch(ctx + '/api/v1/owner/menu-items', { method: 'POST', body: body })\r\n");
      out.write("                .then(() => { done++; progress.textContent = 'Adding dishes... ' + done + ' / ' + items.length; })\r\n");
      out.write("                .catch(() => { done++; });\r\n");
      out.write("        }));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    progress.textContent = 'Done! Added ' + done + ' dishes.';\r\n");
      out.write("    seedBtn.disabled = false;\r\n");
      out.write("    await loadDishes();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("async function doLogout() {\r\n");
      out.write("    try { await fetch(ctx + '/api/v1/logout', { method: 'POST' }); } catch (e) { console.error('Logout request failed', e); }\r\n");
      out.write("    window.location.href = ctx + '/login.jsp';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("loadDishes();\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
