/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-09-20 15:42:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    String role = (String) session.getAttribute("userRole");
    if (role == null) role = "CUSTOMER";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Order History - BenedictJeromeMart</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .order-card { border: 1px solid var(--border); padding: 1rem; margin-bottom: 1rem; border-radius: 8px; background: var(--bg-card); }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"padding:2rem;max-width:800px;margin:0 auto;background:var(--bg-main);\">\r\n");
      out.write("    <h2>Order History</h2>\r\n");
      out.write("    <p style=\"margin-bottom: 1.5rem;\"><a href=\"home.jsp\" style=\"color:var(--primary);font-weight:bold;\">&larr; Back to Home</a></p>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"ordersList\">Loading...</div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        const ctx = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("        const myRole = '");
      out.print( role );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("        async function loadOrders() {\r\n");
      out.write("            const res = await fetch(ctx + '/api/v1/orders/history');\r\n");
      out.write("            const result = await res.json();\r\n");
      out.write("            const container = document.getElementById('ordersList');\r\n");
      out.write("\r\n");
      out.write("            if (!result.success || result.data.length === 0) {\r\n");
      out.write("                container.innerHTML = '<p>No orders yet.</p>';\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            container.innerHTML = '';\r\n");
      out.write("            result.data.forEach(order => {\r\n");
      out.write("                const div = document.createElement('div');\r\n");
      out.write("                div.className = 'order-card';\r\n");
      out.write("\r\n");
      out.write("                const whoLine = myRole === 'RESTAURANT_OWNER'\r\n");
      out.write("                    ? 'Buyer: <strong>' + order.buyerName + '</strong>'\r\n");
      out.write("                    : 'Restaurant: <strong>' + order.restaurantName + '</strong>';\r\n");
      out.write("\r\n");
      out.write("                let itemsHtml = '';\r\n");
      out.write("                if (order.items && order.items.length > 0) {\r\n");
      out.write("                    itemsHtml = '<ul style=\"margin:8px 0;padding-left:18px;font-size:0.9rem;color:var(--text-muted);\">' +\r\n");
      out.write("                        order.items.map(i => '<li>' + i.name + ' x' + i.quantity + '</li>').join('') +\r\n");
      out.write("                        '</ul>';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                let inner =\r\n");
      out.write("                    '<div style=\"display:flex;justify-content:space-between;margin-bottom:0.5rem;\">' +\r\n");
      out.write("                        '<strong>Order #' + order.id + '</strong>' +\r\n");
      out.write("                        '<span style=\"color:var(--primary);font-weight:700;\">' + order.status + '</span>' +\r\n");
      out.write("                    '</div>' +\r\n");
      out.write("                    whoLine + '<br>' +\r\n");
      out.write("                    'Total: Rs.' + order.totalAmount + '<br>' +\r\n");
      out.write("                    '<small style=\"color:var(--text-muted);\">Placed: ' + (order.createdAt || '') + '</small>' +\r\n");
      out.write("                    itemsHtml;\r\n");
      out.write("\r\n");
      out.write("                if (myRole === 'RESTAURANT_OWNER') {\r\n");
      out.write("                    if (order.status !== 'DELIVERED' && order.status !== 'CANCELLED') {\r\n");
      out.write("                        inner += '<button class=\"btn btn-outline-sm\" style=\"margin-top:0.5rem;\" onclick=\"advanceStatus(' + order.id + ')\">Advance to Next Status</button>';\r\n");
      out.write("                    }\r\n");
      out.write("                } else if (order.status === 'DELIVERED') {\r\n");
      out.write("                    inner += '<button class=\"btn btn-outline-sm\" style=\"margin-top:0.5rem;\" onclick=\"leaveReview(' + order.restaurantId + ')\">Leave a Review</button>';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                div.innerHTML = inner;\r\n");
      out.write("                container.appendChild(div);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        async function advanceStatus(orderId) {\r\n");
      out.write("            const formData = new URLSearchParams();\r\n");
      out.write("            formData.append('orderId', orderId);\r\n");
      out.write("            const res = await fetch(ctx + '/api/v1/owner/orders/status', { method: 'POST', body: formData });\r\n");
      out.write("            const result = await res.json();\r\n");
      out.write("            if (!result.success) alert(result.error.message);\r\n");
      out.write("            loadOrders();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        async function leaveReview(restaurantId) {\r\n");
      out.write("            const rating = prompt('Rate this restaurant 1-5:');\r\n");
      out.write("            if (!rating || rating < 1 || rating > 5) return;\r\n");
      out.write("            const comment = prompt('Leave a comment (optional):') || '';\r\n");
      out.write("\r\n");
      out.write("            const formData = new URLSearchParams();\r\n");
      out.write("            formData.append('restaurantId', restaurantId);\r\n");
      out.write("            formData.append('rating', rating);\r\n");
      out.write("            formData.append('comment', comment);\r\n");
      out.write("\r\n");
      out.write("            const res = await fetch(ctx + '/api/v1/reviews', { method: 'POST', body: formData });\r\n");
      out.write("            const result = await res.json();\r\n");
      out.write("            alert(result.success ? 'Thanks for your review!' : result.error.message);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        loadOrders();\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
